// ── State ────────────────────────────────────────────────────────────────
// Shared webview state: a single mutable object so every module reads and
// writes the same instance. DOM refs start `null` and are filled in init().

export const state = {
  connected: false,
  sessions: [],
  activeSessionId: null,
  busy: false,
  stopping: false,
  stoppedStream: false,
  loading: true,
  pendingAssistantId: null,
  pendingUserEl: null,
  catalog: null,
  agent: null,
  model: null,
  usage: null,
  subagents: [],
  subagentsVisible: false,
  pendingPermission: null,
  pendingQuestion: null,
  // DOM refs (filled in init)
  app: null,
  disconnected: null,
  conversation: null,
  sessionList: null,
  sessionCount: null,
  sessionToggle: null,
  progress: null,
  emptyNoSessions: null,
  emptyConversation: null,
  input: null,
  sendBtn: null,
  newSessionBtn: null,
  retryBtn: null,
  emptyNewBtn: null,
  toast: null,
  agentPickerBtn: null,
  agentBadgeValue: null,
  modelPickerBtn: null,
  modelBadgeValue: null,
  thinkingToggle: null,
  thinkingToggleValue: null,
  contextUsageLine: null,
  showThinking: false,
  subagentsToggle: null,
  permissionCard: null,
  questionCard: null,
  slashPopup: null,
  atPopup: null,
  files: null,
  agentMenu: null,
  modelMenu: null,
  helpOverlay: null,
  helpList: null,
};
